---
- hosts: all
  become: true
  vars:
          users: [itescia, itesciadmin, sangeerthan, test]
          package: [htop, vim]

  tasks:
  - name: "add user itescia"
    user:
       name: "{{ item }}"
       create_home: yes
    with_items: "{{ users }}"
   


  - name: "install package"
    package:
       name: "{{ item }}"
       state: present
    with_items: "{{ package }}"
 
  - name: "ssh-key"
    authorized_key:
            user: "{{ item }}"
            key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
            exclusive: true
    with_items: "{{ users }}"

