all:
        hosts:
                backup:
                        ansible_host: 10.0.0.101
                        ansible_ssh_user: itescia       
                dns:
                        ansible_host: 10.0.0.102
                        ansible_ssh_user: itesciadmin       
                web:
                        ansible_host: 10.0.0.103
                        ansible_ssh_user: itesciadmin       
                gateway:
                        ansible_host: 10.0.0.254
                        ansible_ssh_user: itesciadmin       
                smtp:   
                        ansible_host: 10.0.0.104
                        ansible_ssh_user: itesciadmin
