---
 - name: "ssh-key"
    authorized_key:
            user: "{{ item }}"
            key: "{{ lookup('file', 'home/itesciadmin/.ssh/id_{{ item }}.pub') }}"
            exclusive: true
    with_items: "{{ users }}"

